from enum import Enum

class ResourceType(Enum):
    UNKNOWN = ...
    ANY = ...
    TOPIC = ...
    GROUP = ...
    BROKER = ...
    TRANSACTIONAL_ID = ...

class ResourcePatternType(Enum):
    UNKNOWN = ...
    ANY = ...
    MATCH = ...
    LITERAL = ...
    PREFIXED = ...
