name: Check

on:
  push:
  pull_request:

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install tox
      run: python -m pip install tox tox-uv

    - name: Setup environment
      run: tox -v --notest -e lint

    - name: Run linters
      run: tox --skip-pkg-install -e lint
